access_key_manager/urls.py
from django.contrib import admin
from django.urls import include, path
from users import views as users_views 


urlpatterns = [
    path('admin/', admin.site.urls),  # Admin site URL
    path('accounts/', include('users.urls')),  # User-related URLs
    path('access-keys/', include('access_keys.urls', namespace="access_keys")),  # Access key-related URLs
    path('', include('users.urls')),  # Root URL, pointing to user-related views
]

handler403 = 'users.views.custom_permission_denied'

access_keys/urls.py
from django.urls import path
from access_keys import api_views, views

app_name = 'access_keys'

urlpatterns = [
    path('purchase-access-key/', views.purchase_access_key_view, name='purchase_access_key'),
    path('initialize-payment/', views.initialize_payment, name='initialize_payment'),
    path('paystack/callback/', views.paystack_callback, name='paystack_callback'),
    path('revoke/<int:key_id>/', views.revoke_access_key_view, name='revoke_access_key'),
    path('api/status/<str:email>/', api_views.check_access_key_status_view, name='key_status'),
]
 

users/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView
from users import views as users_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', users_views.home, name='home'),  # Home page

    path('school-dashboard/', users_views.school_dashboard_view, name='school_dashboard'),  # School dashboard
    path('admin-dashboard/', users_views.admin_dashboard_view, name='admin_dashboard'),  # Admin dashboard

    path('register/', users_views.registration_options_view, name='register_options'),  # Registration options
    path('register/school/', users_views.register_view, {'user_type': 'school_personnel'}, name='register_school_personnel'),  # School personnel registration
    path('register/admin/', users_views.register_view, {'user_type': 'admin'}, name='register_admin'),  # Admin registration
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),  # Account activation
    path('registration_pending/', TemplateView.as_view(template_name='authentication/registration_pending.html'), name='registration_pending'),  # Registration pending page
    path('activation_success/', TemplateView.as_view(template_name='authentication/activation_success.html'), name='activation_success'),  # Activation success page
    path('activation_invalid/', TemplateView.as_view(template_name='authentication/activation_invalid.html'), name='activation_invalid'),  # Activation invalid page

    path('login/', users_views.login_view, name='login'),  # Login
    path('logout/', users_views.logout_view, name='logout'),  # Logout

    path('profile/', users_views.profile_view, name='profile'),  # Profile
    path('profile/complete/', users_views.complete_profile_view, name='complete_profile'),  # Complete profile
    path('profile/update/', users_views.update_profile_view, name='update_profile'),  # Update profile
    path('profile/billing-info/', users_views.billing_information_view, name='billing_information'),  # Billing information
    path('profile/billing-info/update/', users_views.update_billing_information_view, name='update_billing_info'),  # Update billing information

    # Password Reset URLs
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='authentication/password_reset_form.html'), name='password_reset'),  # Password reset
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='authentication/password_reset_done.html'), name='password_reset_done'),  # Password reset done
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='authentication/password_reset_confirm.html'), name='password_reset_confirm'),  # Password reset confirm
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='authentication/password_reset_complete.html'), name='password_reset_complete'),  # Password reset complete

    # Password Change URLs
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='authentication/password_change_form.html'), name='password_change'),  # Password change
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='authentication/password_change_done.html'), name='password_change_done'),  # Password change done
]

access_keys/models.py
import logging
from django.core.exceptions import ValidationError
from django.db import models
from users.models import School, User


logger = logging.getLogger(__name__)

def validate_active_key(access_key):
    """
    Validates that a school can have only one active access key at a time.

    Args:
        access_key (AccessKey): The AccessKey instance to be validated.

    Raises:
        ValidationError: If the school already has an active access key.
        
    Example:
        >>> key = AccessKey(school=school, status='active')
        >>> validate_active_key(key)
    """
    school = access_key.school
    active_keys = school.access_keys.filter(status='active')
    if active_keys.exists() and access_key.status == 'active':
        logger.warning(f"School {school.name} already has an active key. Attempt to create another active key.")
        raise ValidationError('A school can have only one active access key at a time.')


class AccessKey(models.Model):
    """
    Model representing an access key for a school.

    Attributes:
        key (CharField): A unique identifier for the access key.
        school (ForeignKey):  References the school that this access key belongs to.
        status (CharField): The current status of the access key.
        assigned_to (ForeignKey): The user to whom this access key is assigned.
        procurement_date (DateTimeField): The date when this access key was procured.
        expiry_date (DateTimeField): The date when this access key expires.
        revoked_by (ForeignKey): The user who revoked this access key.
        revoked_on (DateTimeField): The date and time when this access key was revoked.
        price (DecimalField): The price of this access key.

    Methods:
        __str__(self): Returns a string representation of the access key.
    """
    key = models.CharField(max_length=20, unique=True)
    school = models.ForeignKey(School, on_delete=models.CASCADE, related_name='access_keys')
    status = models.CharField(max_length=10,
                               choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked')],
                               validators=[validate_active_key])

    assigned_to = models.ForeignKey(User, on_delete=models.CASCADE, related_name='access_keys')
    procurement_date = models.DateTimeField(auto_now_add=True)
    expiry_date = models.DateTimeField()
    revoked_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='revoked_access_keys')
    revoked_on = models.DateTimeField(null=True, blank=True)
    price = models.DecimalField(max_digits=8, decimal_places=2)

    def __str__(self):
        return f"{self.key} - {self.school.name} - {self.status}"
    
    
class KeyLog(models.Model):
    """
    Model representing a log entry for an action performed on an access key.

    Attributes:
        action (CharField): A description of the action performed on the access key.
        user (ForeignKey): The user who performed the action.
        access_key (ForeignKey): The access key on which the action was performed.
        timestamp (DateTimeField): The timestamp when the action was performed.
    """

    action = models.CharField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    access_key = models.ForeignKey(AccessKey, on_delete=models.CASCADE, related_name='key_logs')
    timestamp = models.DateTimeField(auto_now_add=True)

users/views.py
import logging
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_str
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.core.mail import send_mail

from django.shortcuts import render, redirect
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth import login as auth_login, logout
from users.forms import ProfileUpdateForm, RegistrationForm, LoginForm, ProfileForm, UpdateBillingInformationForm
from users.helpers import user_passes_test_with_403, is_school_personnel, is_admin
from users.contexts import common_context_data
from users.models import BillingInformation, User
from access_keys.models import AccessKey, KeyLog
from django.contrib import messages
from django.conf import settings


logger = logging.getLogger(__name__)

def custom_permission_denied(request, exception):
    """
    This function renders a 403 Forbidden page with an error message and additional information.

    Args:
        request (HttpRequest): The HTTP request object.
        exception (Exception): The exception that caused the permission denial.

    Returns:
        HttpResponse: A rendered HTML response containing the 403 Forbidden page.

     Returns:
        HttpResponse: A rendered HTML response with a 403 Forbidden status.
    """
    context = {
        'error_message': str(exception) or 'You do not have permission to access this page.',
        'additional_info': 'Please contact an administrator if you believe this is an error.'
    }
    return render(request, 'errors/403.html', context, status=403)


def home(request):
    """
    This function renders the home page for authenticated users.

    Args:
        request: The HTTP request object.

    Returns:
        A rendered HTML response containing the home page.
    """
    context = common_context_data(request)
    logger.info("Rendering home page for user %s", request.user.username)
    return render(request, 'users/home.html', context)


@login_required
@user_passes_test_with_403(is_school_personnel)
def school_dashboard_view(request):
    """
    Renders the school dashboard page for authenticated school personnel.

    Args:
        request: The HTTP request object.

    Returns:
        A rendered HTML response containing the school dashboard page.
    """
    user = request.user
    if not user.is_profile_complete():
        logger.warning("User %s attempted to access school dashboard without a complete profile.", user.username)
        messages.error(request, 'Please complete your profile to access the school dashboard.')
        return redirect('complete_profile')

    try:
        school = user.school
        access_keys = school.access_keys.order_by('-procurement_date')
        logger.info("User %s accessed school dashboard.", user.username)
    except ObjectDoesNotExist:
        logger.error("No school associated with user %s", user.username)
        messages.error(request, 'No school associated with your account. Please complete your profile.')
        return redirect('complete_profile')

    context = common_context_data(request)
    context.update({
        'school': school,
        'access_keys': access_keys,
    })
    return render(request, 'users/school_dashboard.html', context)

@login_required
@user_passes_test_with_403(is_admin)
def admin_dashboard_view(request):
    """
    Renders the admin dashboard page for authenticated admin users.

    Args:
        request: The HTTP request object.

    Returns:
        A rendered HTML response containing the admin dashboard page.
    """
    user = request.user
    if not user.is_profile_complete():
        logger.warning("User %s attempted to access admin dashboard without a complete profile.", user.username)
        messages.error(request, 'Please complete your profile to access the admin dashboard.')
        return redirect('complete_profile')

    access_keys = AccessKey.objects.order_by('-procurement_date')
    key_logs = KeyLog.objects.order_by('-timestamp')
    logger.info("User %s accessed admin dashboard.", user.username)

    context = common_context_data(request)
    context.update({
        'access_keys': access_keys,
        'key_logs': key_logs,
    })
    return render(request, 'users/admin_dashboard.html', context)


def registration_options_view(request):
    """
    Renders the registration options page, where users choose whether they are school personnel or admin.

    Args:
        request: The HTTP request object.

    Returns:
        A rendered HTML response containing the registration options page.
    """
    logger.info("Rendering registration options page.")
    return render(request, 'accounts/register_options.html')


def register_view(request, user_type):
    """
    Handles the registration process for new users.

    Args:
        request: The HTTP request object.
        user_type: The type of user being registered ('school_personnel' or 'admin').

    Returns:
        A rendered HTML response containing the registration form or redirects on success.

    Raises:
        ValueError: If the provided user_type is invalid.

    The function processes the registration form, creates a new inactive user,
    sets the appropriate user type, and sends a verification email.
    """
    if request.method == "POST":
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            if user_type == 'school_personnel':
                user.is_school_personnel = True
            elif user_type == 'admin':
                user.is_admin = True
            user.save()
            send_verification_email(request, user)
            logger.info("Registration successful for user %s. Verification email sent.", user.username)
            messages.success(request, 'Registration successful. Please confirm your email.')
            return redirect('registration_pending')
        else:
            for field, errors in form.errors.items():
                for error in errors:
                    messages.error(request, f"{field.capitalize()}: {error}")
            logger.warning("Registration form is invalid: %s", form.errors)
    else:
        form = RegistrationForm()
    logger.info("Rendering registration form for %s user type.", user_type)
    return render(request, 'accounts/register.html', {'form': form})


def send_verification_email(request, user):
    """
    This function sends a verification email to the newly registered user.

    Args:
        request: The HTTP request object.
        user: The newly registered user.
    """
    current_site = get_current_site(request)
    mail_subject = 'Activate your account.'
    message = render_to_string('authentication/acc_active_email.html', {
        'user': user,
        'domain': current_site.domain,
        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
        'token': account_activation_token.make_token(user),
    })
    to_email = user.email
    send_mail(mail_subject, message, settings.DEFAULT_FROM_EMAIL, [to_email])
    logger.info("Sent verification email to %s", to_email)

def activate(request, uidb64, token):
    """
    Activates the user's account after clicking the verification link.

    Args:
        request: The HTTP request object.
        uidb64: The base64-encoded user ID.
        token: The activation token.

    Returns:
         HttpResponse: Redirect to login on success, otherwise activation failure page.
    """
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        logger.info("User %s activated successfully.", user.username)
        messages.success(request, 'Your account has been activated successfully!')
        return redirect('activation_success')
    else:
        logger.error("Activation link is invalid for user.")
        messages.error(request, 'Activation link is invalid!')
        return render(request, 'authentication/activation_invalid.html')


def login_view(request):
    """
    Handles the user login  by rendering the login form and authenticating users.

    Args:
        request: The HTTP request object.

    Returns:
        HttpResponse: The rendered login page or redirect to home on success.
    """
    if request.method == "POST":
        form = LoginForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            auth_login(request, user)
            logger.info("User %s logged in successfully.", user.username)
            messages.success(request, 'Login successful.')
            return redirect('home')
        else:
            logger.warning("Login attempt failed for user.")
            messages.error(request, 'Login failed. Please check your credentials.')
    else:
        form = LoginForm()
        logger.info("Rendering login page.")
    return render(request, 'accounts/login.html', {'form': form})


@login_required
def logout_view(request):
    """
    This function logs out the user and redirects to the home page.

    Args:
        request: The HTTP request object.

    Returns:
        HttpResponse: Redirect to home page.
    """
    logout(request)
    logger.info("User %s logged out successfully.", request.user.username)
    messages.success(request, 'Logout successful.')
    return redirect('home')


@login_required
def profile_view(request):
    """
    Renders the user profile page.

    Args:
        request: The HTTP request object.

    Returns:

templates/users/admin_dashboard.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Admin Dashboard{% endblock %}

{% block content %}
  <div class="back">
    <a href="{% url 'home' %}">
        <i class="fas fa-arrow-left"></i>Home
    </a>
  </div>
  <div class="mt-4">
    <h1>Admin Dashboard</h1>

    <div class="alert alert-info">
      <p>Welcome, {{ request.user.get_full_name }}</p>
    </div>

    <div class="mt-3">
    <h2>Access Keys</h2>
    {% if access_keys %}
    <div class="table-responsive">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Key</th>
            <th>School</th>
            <th>Status</th>
            <th>Procurement Date</th>
            <th>Expiry Date</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody class="table-group-divider">
          {% for access_key in access_keys %}
            <tr class="access-key-{{ access_key.status }}">
              <td>{{ access_key.key }}</td>
              <td>{{ access_key.school.name }}</td>
              <td>{{ access_key.get_status_display }}</td>
              <td>{{ access_key.procurement_date|date:"F j, Y" }}</td>
              <td>{{ access_key.expiry_date|date:"F j, Y" }}</td>
              <td>
                {% if access_key.status == 'active' %}
                  <a href="{% url 'access_keys:revoke_access_key' access_key.id %}" class='btn btn-primary'>Revoke</a>
                {% endif %}
              </td>
            </tr>
          {% endfor %}
        </tbody> 
      </table>
    </div>
    {% else %}
      <p>No access keys found.</p>
    {% endif %}
    </div>    

    <!-- Key Logs Section -->
    <div class="mt-4">
      <button id="toggle-log" class="btn btn-info">View Logs</button>
      <div id="key-log">
        <h2>Key Logs</h2>
        <div class="table-responsive">
          <table class="table table-hover mt-3">
            <thead>
              <tr>
                <th>User</th>
                <th>Action</th>
                <th>Timestamp</th>
              </tr>
            </thead>
            <tbody class="table-group-divider">
              {% for log in key_logs %}
                <tr>
                  <td>{{ log.user.get_full_name }}</td>
                  <td>{{ log.action }}</td>
                  <td>{{ log.timestamp }}</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
      <a href="{% url 'logout' %}" class="btn btn-secondary mt-3">Logout</a>
    </div>
  </div>
{% endblock %}

{% block scripts %}
<script src="{% static 'js/keyLogs.js' %}"></script>
{% endblock %}

templates/users/billing_information.html
{% extends 'base.html' %}

{% block title %}Payment Details{% endblock %}

{% block content %}
<div class="container">
    <div class="back">
        <a href="{% url 'profile' %}">
            <i class="fas fa-arrow-left"></i>Profile
        </a>
    </div>
    <div class="mt-4">
        <h4>Payment Details</h4>
        {% if billing_info %}
            <p><strong>Payment Method:</strong> {{ billing_info.get_payment_method_display }}</p>
            {% if billing_info.payment_method == "card" %}
                <p><strong>Card Number:</strong> **** **** **** {{ billing_info.card_number|slice:"-4:" }}</p>
                <p><strong>Expiry:</strong> {{ billing_info.card_expiry }}</p>
                <p><strong>CVV:</strong> ***</p>
            {% elif billing_info.payment_method == "mtn_momo" %}
                <p><strong>Mobile Money Number:</strong> {{ billing_info.mobile_money_number }}</p>
            {% endif %}
        {% else %}
            <p>No details found.</p>
        {% endif %}
    </div>
    <div class="mt-4">
        <a href="{% url 'update_billing_info' %}" class="btn btn-primary">Update Payment Details</a>
    </div>
</div>
{% endblock %}

templates/users/complete_profile.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block title %}Complete Profile{% endblock title %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-lg-6 col-md-8 col-sm-10">
        <div class="mt-3 text-center">
            <h3>Complete Your Profile</h3>
        </div>
        <div class="card">
            <div class="card-body">
                <form method="POST" novalidate>
                    {% csrf_token %}
                    {{ form|crispy }}
                    <div class="d-grid mt-3">
                        <button type="submit" class="btn btn-primary btn-block">Submit Profile</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/users/home.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
  <div class="container-fluid">
    <!-- Welcome Message -->
    <h1>Welcome to Access Key Manager</h1>
    <p class="lead">Manage your school's access keys easily and securely.</p>

    <!-- Display different content based on authentication status -->
    {% if user.is_authenticated %}
      <div class="alert alert-success">
        {% if user.is_admin %}
          <p>You are logged in as an admin.</p>
          <a href="{% url 'admin_dashboard' %}" class="btn btn-primary">Go to Admin Dashboard</a>
        {% elif user.is_school_personnel %}
          <p>You are logged in as school personnel for {{ user.school.name }}.</p>
          <a href="{% url 'school_dashboard' %}" class="btn btn-primary">Go to School Dashboard</a>
        {% endif %}
      </div>
      <a href="{% url 'logout' %}" class="btn btn-secondary">Logout</a>
    {% else %}
      <div class="alert alert-info">
        <p>Please log in or register to access the application.</p>
        <a href="{% url 'login' %}" class="btn btn-primary">Login</a>
        <a href="{% url 'register_options' %}" class="btn btn-secondary">Register</a>
      </div>
    {% endif %}
  </div>
{% endblock %}

templates/users/profile.html
{% extends 'base.html' %}

{% block title %}Profile{% endblock %}

{% block content %}
<div class="container">
    <div class="back">
        {% if user.is_school_personnel %}
        <a href="{% url 'school_dashboard' %}">
            <i class="fas fa-arrow-left"></i>Dashboard
        </a>
        {% else %}
        <a href="{% url 'admin_dashboard' %}">
            <i class="fas fa-arrow-left"></i>Dashboard
        </a>
        {% endif %}
    </div>
    <div class="mt-3" id="profile">
        <div class="profile-item">
            <h2>Profile</h2>
            <p><strong>Username:</strong> @{{ user.username }}</p>
            <p><strong>Email:</strong> {{ user.email }}</p>
            <p><strong>First Name:</strong> {{ user.first_name }}</p>
            <p><strong>Last Name:</strong> {{ user.last_name }}</p>
            {% if user.is_admin %}
            <p><strong>Staff ID:</strong> {{ user.staff_id }}</p>
            <div class="mt-3">
                <a href="{% url 'update_profile' %}" class="btn btn-primary">Update Profile</a>
            </div>
            {% elif user.is_school_personnel %}
                {% if user.school %}
                    <p><strong>School:</strong> {{ user.school.name }}</p>
                    <div class="mt-3">
                        <a href="{% url 'update_profile' %}" class="btn btn-primary">Update Profile</a>
                    </div>
    
        </div>
        <div class="profile-item">
                <h2>Active Access Key</h2>
                {% if active_key %}
                    <p><strong>Key:</strong> {{ active_key.key }}</p>
                    <p><strong>Status:</strong> {{ active_key.status }}</p>
                    <p><strong>Procurement Date:</strong> {{ active_key.procurement_date|date:"F j, Y" }}</p>
                    <p><strong>Expiry Date:</strong> {{ active_key.expiry_date|date:"F j, Y" }}</p>
                    {% else %}
                        <p>No active access key found.</p>
                    {% endif %}
                {% else %}
                    <p>No school associated with your profile. Please <a href="{% url 'complete_profile' %}">complete your profile</a>.</p>
                {% endif %}
            {% endif %}
            <div class="mt-3">
                {% if user.is_school_personnel %}
                <a href="{% url 'billing_information' %}" class="btn btn-info">View Payment Details</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/users/school_dashboard.html
{% extends 'base.html' %}

{% block title %}School Dashboard{% endblock %}

{% block content %}
  <div class="back">
      <a href="{% url 'home' %}">
          <i class="fas fa-arrow-left"></i>Home
      </a>
  </div>
  <div class="mt-4">
    <h1>School Dashboard</h1>

    <div class="alert alert-info">
      <p>Welcome, {{ request.user.get_full_name }}{% if school %} ({{ school.name }}){% endif %}</p>
    </div>
  
    <h2>Access Keys</h2>
    {% if access_keys %}
    <div class="table-responsive">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Key</th>
            <th>Status</th>
            <th>Procurement Date</th>
            <th>Expiry Date</th>
          </tr>
        </thead>
        <tbody class="table-group-divider">
          {% for access_key in access_keys %}
            <tr class="access-key-{{ access_key.status }}">
              <td>{{ access_key.key }}</td>
              <td>{{ access_key.get_status_display }}</td>
              <td>{{ access_key.procurement_date|date:"F j, Y" }}</td>
              <td>{{ access_key.expiry_date|date:"F j, Y" }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    {% else %}
      <p>No access keys found.</p>
    {% endif %}
    {% if not active_access_key %}
      <a href="{% url 'access_keys:purchase_access_key' %}" class="btn btn-primary">Purchase Access Key</a>
    {% endif %}
  
    <a href="{% url 'logout' %}" class="btn btn-secondary">Logout</a>
  </div>
{% endblock content %}

templates/users/update_billing_info.html
{% extends 'base.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% block content %}
<div class="row justify-content-center mt-4">
    <div class="col-lg-6 col-md-8 col-sm-10">
        <div class="text-center">
            <h4>Update Payment Details</h4>
        </div>
        <div class="card mt-3">
            <div class="card-body mt-4">
                <form method="post" novalidate>
                    {% csrf_token %}
                    {{ form.payment_method|as_crispy_field }}
                    <!-- Card fields, hidden initially -->
                    <div id="card-fields" style="display: none;">
                      {{ form.card_number|as_crispy_field }}
                      {{ form.card_expiry|as_crispy_field }}
                      {{ form.card_cvv|as_crispy_field }}
                    </div>
                    <!-- Mobile Money fields, hidden initially -->
                    <div id="momo-fields" style="display: none;">
                      {{ form.mobile_money_number|as_crispy_field }}
                    </div>
                    <div class="mt-3">
                        <button type="submit" class="btn btn-primary">Save Changes</button>
                        <a href="{% url 'billing_information' %}" class="btn btn-secondary">Cancel</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script src="{% static 'js/update_billing.js' %}"></script>
{% endblock %}

templates/users/update_profile.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}Update Profile{% endblock %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-lg-6 col-md-8 col-sm-10">
        <div class="mt-3 text-center">
            <h4>Update Profile</h4>
        </div>
        <div class="card">
            <div class="card-body">
                <form method="POST" novalidate>
                    {% csrf_token %}
                    {{ profile_form|crispy }}
                    <div class="mt-3">
                        <button type="submit" class="btn btn-primary">Save Changes</button>
                        <a href="{% url 'profile' %}" class="btn btn-secondary">Cancel</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}